const WIND_NAMES={taipei:"臺北 466920",xinyi:"信義 C0AC70",songshan_cwa:"松山 C0AH70",wenshan:"文山 C0AC80",neihu:"內湖 C0A9F0",yonghe:"永和 C0AH10"};
const PM_NAMES={sp05_hourly:"SP-05 小時值",songshan:"松山 EPA",zhongshan:"中山 EPA",wanhua:"萬華 EPA",guting:"古亭 EPA",shilin:"士林 EPA",yangming:"陽明 EPA"};
const PM_STATIONS={sp05_hourly:{name:"SP-05",lat:25.044,lng:121.562},songshan:{name:"松山",lat:25.0497,lng:121.5775},zhongshan:{name:"中山",lat:25.0632,lng:121.5236},wanhua:{name:"萬華",lat:25.0313,lng:121.4992},guting:{name:"古亭",lat:25.020,lng:121.530},shilin:{name:"士林",lat:25.0870,lng:121.5233},yangming:{name:"陽明",lat:25.1773,lng:121.5447}};
Object.entries(WIND_PM25_DATA.pm25_stations||{}).forEach(([k,m])=>{if(!PM_NAMES[k])PM_NAMES[k]=m.name||k;if(!PM_STATIONS[k]&&m.lat!=null&&m.lng!=null)PM_STATIONS[k]={name:m.name||k,lat:m.lat,lng:m.lng}});
const WIND_STATIONS={taipei:{name:"臺北",lat:25.037658,lng:121.514853},xinyi:{name:"信義",lat:25.037822,lng:121.566545},songshan_cwa:{name:"松山",lat:25.048482,lng:121.550267},wenshan:{name:"文山",lat:24.988315,lng:121.562447},neihu:{name:"內湖",lat:25.079422,lng:121.575450},yonghe:{name:"永和",lat:25.017000,lng:121.516000}};
const DIR16=["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"];
const SPEED_BINS=[0.5,1,2,3,5,8,99];
let map,lagChart,seriesChart,selectedEvent=0;
const pmMarkers={},windMarkers={};

function pad(n){return String(n).padStart(2,"0")}
function parseT(t){return new Date(t+":00")}
function fmtT(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:00`}
function addHours(t,h){const d=parseT(t);d.setHours(d.getHours()+h);return fmtT(d)}
function pmColor(v){if(v==null)return"#334155";if(v<12)return"#45c486";if(v<35)return"#f2b84b";if(v<54)return"#f47b45";return"#ef5350"}
function pmRadius(v){return v==null?7:Math.max(8,Math.min(25,7+v*.32))}
function wdIndex(wd){return Math.round((wd%360)/22.5)%16}
function wdName(wd){return wd==null?"--":DIR16[wdIndex(wd)]}
function zhClass(label){return{"regional/transport":"區域/傳輸","transport possible":"可能傳輸","transport":"傳輸","stagnation":"停滯累積","regional":"區域同步","humidity-influenced":"濕度影響","local/mixed":"局部/混合","Stagnation":"停滯累積","Regional":"區域同步","Transport":"傳輸","Local/mixed":"局部/混合"}[label]||label}
function zhFlag(flag){return{regional_sync:"多站同步",stagnation:"靜風停滯",humid_growth_possible:"高濕可能影響",near_saturation:"接近飽和",rain_affected:"受降雨影響",transport_plausible:"傳輸條件成立"}[flag]||flag}
function pearson(xs,ys){const n=xs.length;if(n<3)return null;const mx=xs.reduce((a,b)=>a+b,0)/n,my=ys.reduce((a,b)=>a+b,0)/n;let vx=0,vy=0,c=0;for(let i=0;i<n;i++){const dx=xs[i]-mx,dy=ys[i]-my;vx+=dx*dx;vy+=dy*dy;c+=dx*dy}return vx&&vy?c/Math.sqrt(vx*vy):null}
function getState(){return{eventIndex:+eventSelect.value,pmKey:pmSelect.value,windKey:windSelect.value,offset:+offsetRange.value,lag:+lagRange.value,calm:+calmInput.value}}
function allEvents(){return (PEAK_DATA?.RANKED||[]).slice(0,14).map(r=>({date:r.date,peakH:r.peakH,peakV:r.peakV,rank:r.rank,avg:r.sp05}))}
function peakTime(e){return `${e.date}T${pad(e.peakH)}:00`}
function eventTime(e,offset=0){return `${e.date}T${pad(Math.max(0,Math.min(23,e.peakH+offset)))}:00`}
function hoursBetween(a,b){return Math.round((parseT(a)-parseT(b))/3600000)}
function relativeToPeak(t,event){const h=hoursBetween(t,peakTime(event));if(h===0)return"高峰當下";return`高峰${h<0?"前":"後"}${Math.abs(h)}小時`}
function lagText(lag){if(lag===0)return"選中時間同時風";return lag>0?`選中時間前 ${lag} 小時風`:`選中時間後 ${Math.abs(lag)} 小時風`}
function pmOffsetText(event,offset){return `${eventTime(event,offset)} (${relativeToPeak(eventTime(event,offset),event)})`}
function windMap(key){const m={};(WIND_PM25_DATA.wind_stations[key]?.records||[]).forEach(r=>m[r.t]=r);return m}
function pmMap(key){const m={};(WIND_PM25_DATA.pm25_data[key]||[]).forEach(r=>m[r.t]=r.v);return m}
function pmValueAt(key,t){const d=t.slice(0,10),h=+t.slice(11,13);const day=PEAK_DATA?.ALL_DATA?.[d];if(day?.hourly?.[key])return day.hourly[key][h]??null;return pmMap(key)[t]??null}
function aligned(st,lag=st.lag){const w=windMap(st.windKey),p=pmMap(st.pmKey),rows=[];Object.entries(p).forEach(([t,pm])=>{const wt=addHours(t,-lag),wr=w[wt];if(pm!=null&&wr&&wr.WD!=null&&wr.WS!=null)rows.push({t,pm,windT:wt,wd:wr.WD,ws:wr.WS,weather:wr})});return rows}
function lagStats(st){const out=[];for(let lag=-6;lag<=6;lag++){const rows=aligned(st,lag),ys=rows.map(r=>r.pm),sin=rows.map(r=>Math.sin(r.wd*Math.PI/180)),cos=rows.map(r=>Math.cos(r.wd*Math.PI/180)),ws=rows.map(r=>r.ws);const c1=pearson(sin,ys),c2=pearson(cos,ys),c3=pearson(ws,ys);out.push({lag,n:rows.length,cSin:c1,cCos:c2,cWs:c3,score:Math.max(Math.abs(c1||0),Math.abs(c2||0),Math.abs(c3||0))})}return out}
function classifyEvent(rows,event,st){const dayRows=rows.filter(r=>r.t>=`${event.date}T00:00`&&r.t<=`${event.date}T23:00`);const calmRatio=dayRows.length?dayRows.filter(r=>r.ws<st.calm).length/dayRows.length:0;const windyHigh=dayRows.filter(r=>r.ws>=2&&r.pm>=35).length;let regional=0,total=0;Object.keys(PM_NAMES).forEach(k=>{const v=pmValueAt(k,eventTime(event,0));if(v!=null){total++;if(v>=25)regional++}});if(calmRatio>.45)return{type:"stagnation",label:"停滯累積",why:`高峰日靜風比例 ${(calmRatio*100).toFixed(0)}%，不適合硬用風向解釋。`};if(total>=4&&regional/total>=.6)return{type:"regional",label:"區域同步",why:`高峰小時有 ${regional}/${total} 個 PM 測站同步偏高。`};if(windyHigh>=2)return{type:"transport",label:"傳輸",why:"高 PM 發生在非靜風條件下，具傳輸可能。"};return{type:"local",label:"局部/混合",why:"空間同步與風場證據不足，可能是局部或混合因素。"}}
function stationMeta(source,key,fallback){const meta=source?.[key]||{};return{...fallback,lat:meta.lat??fallback.lat,lng:meta.lng??fallback.lng,name:fallback.name}}
function makePmIcon(value){const size=pmRadius(value)*2,txt=value==null?"NA":Math.round(value),cls=value==null?"pm-bubble na":"pm-bubble";return L.divIcon({className:"pm-map-icon",html:`<div class="${cls}" style="background:${pmColor(value)}">${txt}</div>`,iconSize:[size,size],iconAnchor:[size/2,size/2]})}
function makeWindIcon(rec,calmThreshold){if(!rec||rec.WD==null||rec.WS==null)return L.divIcon({className:"wind-map-icon",html:`<div class="wind-shell"><div class="wind-disc missing">NA</div></div>`,iconSize:[44,44],iconAnchor:[22,22]});if(rec.WS<calmThreshold)return L.divIcon({className:"wind-map-icon",html:`<div class="wind-shell"><div class="wind-disc calm">calm</div></div>`,iconSize:[44,44],iconAnchor:[22,22]});const size=Math.max(44,Math.min(74,34+rec.WS*9)),travel=(rec.WD+180)%360;const html=`<div class="wind-shell"><div class="wind-disc" style="width:${size}px;height:${size}px"><svg class="wind-arrow-svg" width="${size-12}" height="${size-12}" viewBox="0 0 40 40" style="transform:rotate(${travel}deg)"><path d="M20 3 L31 30 L20 24 L9 30 Z" fill="#20c6d7" stroke="#e0faff" stroke-width="1.4"/></svg></div></div>`;return L.divIcon({className:"wind-map-icon",html,iconSize:[size,size],iconAnchor:[size/2,size/2]})}
function initMap(){map=L.map("map",{zoomControl:true,attributionControl:false}).setView([25.063,121.535],12);L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{maxZoom:19}).addTo(map);Object.keys(PM_STATIONS).forEach(k=>{const meta=stationMeta(WIND_PM25_DATA.pm25_stations,k,PM_STATIONS[k]);pmMarkers[k]=L.marker([meta.lat,meta.lng],{icon:makePmIcon(null),zIndexOffset:600,title:meta.name}).addTo(map)});Object.keys(WIND_STATIONS).forEach(k=>{const meta=stationMeta(WIND_PM25_DATA.wind_stations,k,WIND_STATIONS[k]);windMarkers[k]=L.marker([meta.lat,meta.lng],{icon:makeWindIcon(null,.5),zIndexOffset:500,title:meta.name}).addTo(map)})}
function drawMap(st,event){const pmT=eventTime(event,st.offset),windT=addHours(pmT,-st.lag),peakT=peakTime(event);let pmConnected=0,windConnected=0;Object.keys(pmMarkers).forEach(k=>{const v=pmValueAt(k,pmT);if(v!=null)pmConnected++;pmMarkers[k].setIcon(makePmIcon(v)).bindPopup(`<b>${PM_NAMES[k]||k}</b><br>高峰時間：${peakT}<br>PM2.5 時間：${pmT}<br>PM2.5：${v==null?"NA":v.toFixed(1)} ug/m3`)});Object.keys(windMarkers).forEach(k=>{const rec=(WIND_PM25_DATA.wind_stations[k]?.records||[]).find(r=>r.t===windT);if(rec&&rec.WD!=null&&rec.WS!=null)windConnected++;const calm=rec&&rec.WS<st.calm;windMarkers[k].setIcon(makeWindIcon(rec,st.calm)).bindPopup(`<b>${WIND_NAMES[k]||k}</b><br>高峰時間：${peakT}<br>風場時間：${windT} (${relativeToPeak(windT,event)})<br>風場標示：${lagText(st.lag)}<br>風向/風速：${!rec?"NA":calm?"靜風":rec.WD+" 度 / "+rec.WS+" m/s"}<br>RH：${rec?.RH??"NA"}%<br>溫度：${rec?.Temp??"NA"} C<br>雨量：${rec?.Precp??"NA"} mm`)});
mapStatus.innerHTML=`<strong>高峰時間</strong>：${peakT}<br><strong>PM2.5 時間</strong>：${pmT} (${relativeToPeak(pmT,event)})<br><strong>風場時間</strong>：${relativeToPeak(windT,event)}，${lagText(st.lag)}<br><span style="color:#63758d">${windT}</span><br><strong>資料連接</strong>：PM ${pmConnected}/${Object.keys(pmMarkers).length}，風站 ${windConnected}/${Object.keys(windMarkers).length}`}
function drawLagChart(stats,currentLag){if(lagChart)lagChart.destroy();lagChart=new Chart(lagChartEl(),{type:"bar",data:{labels:stats.map(s=>lagText(s.lag)),datasets:[{data:stats.map(s=>s.score),backgroundColor:stats.map(s=>s.lag===currentLag?"#f2b84b":"#5b8cff88"),borderColor:"#5b8cff",borderWidth:1}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{afterBody:(items)=>{const s=stats[items[0].dataIndex];return[`配對數=${s.n}`,`sinWD=${(s.cSin??0).toFixed(3)}`,`cosWD=${(s.cCos??0).toFixed(3)}`,`風速=${(s.cWs??0).toFixed(3)}`]}}}},scales:{x:{ticks:{color:"#93a4ba",maxRotation:45,minRotation:35},grid:{color:"#26364f"}},y:{min:0,max:.6,ticks:{color:"#93a4ba"},grid:{color:"#26364f"}}}}})}
function lagChartEl(){return document.getElementById("lagChart")}
function drawSeries(rows,event){const start=`${event.date}T00:00`,end=`${event.date}T23:00`;let pts=rows.filter(r=>r.t>=start&&r.t<=end);if(!pts.length)pts=rows.slice(-160);if(seriesChart)seriesChart.destroy();seriesChart=new Chart(document.getElementById("seriesChart"),{type:"line",data:{labels:pts.map(r=>r.t.slice(11,16)),datasets:[{label:"PM2.5",data:pts.map(r=>r.pm),borderColor:"#a879ff",backgroundColor:"rgba(168,121,255,.1)",fill:true,tension:.25,pointRadius:2,yAxisID:"y"},{label:"延遲風速",data:pts.map(r=>r.ws),borderColor:"#20c6d7",borderDash:[4,3],tension:.25,pointRadius:2,yAxisID:"y2"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#93a4ba"}}},scales:{x:{ticks:{color:"#63758d"},grid:{color:"#26364f"}},y:{min:0,ticks:{color:"#93a4ba"},grid:{color:"#26364f"}},y2:{position:"right",min:0,ticks:{color:"#20c6d7"},grid:{drawOnChartArea:false}}}}})}
function drawPolar(rows,st){const c=document.getElementById("polar"),ctx=c.getContext("2d"),cx=c.width/2,cy=c.height/2,rMax=122;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#0e1528";ctx.fillRect(0,0,c.width,c.height);const bins=Array.from({length:16},()=>Array.from({length:SPEED_BINS.length},()=>[]));rows.forEach(r=>{if(r.ws<st.calm)return;const si=SPEED_BINS.findIndex(b=>r.ws<=b);bins[wdIndex(r.wd)][si].push(r.pm)});for(let d=0;d<16;d++){const a0=(d*22.5-11.25-90)*Math.PI/180,a1=(d*22.5+11.25-90)*Math.PI/180;for(let s=0;s<SPEED_BINS.length;s++){const inner=rMax*s/SPEED_BINS.length,outer=rMax*(s+1)/SPEED_BINS.length,vals=bins[d][s],mean=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;ctx.beginPath();ctx.arc(cx,cy,outer,a0,a1);ctx.arc(cx,cy,inner,a1,a0,true);ctx.closePath();ctx.fillStyle=vals.length<2?"#17243a":pmColor(mean);ctx.globalAlpha=vals.length<2?.55:.9;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle="#0b1020";ctx.stroke()}}ctx.fillStyle="#93a4ba";ctx.font="11px Segoe UI";ctx.textAlign="center";["N","E","S","W"].forEach((d,i)=>{const a=(i*90-90)*Math.PI/180;ctx.fillText(d,cx+Math.cos(a)*(rMax+16),cy+Math.sin(a)*(rMax+16)+4)});for(let s=1;s<=SPEED_BINS.length;s++){ctx.beginPath();ctx.arc(cx,cy,rMax*s/SPEED_BINS.length,0,Math.PI*2);ctx.strokeStyle="rgba(147,164,186,.18)";ctx.stroke()}}
function eventDiagnosis(event,st){const data=typeof EVENT_DIAGNOSIS_DATA==="undefined"?null:EVENT_DIAGNOSIS_DATA;const ev=data?.events?.find(e=>e.date===event.date&&e.peak_hour===event.peakH);return ev?.wind?.[st.windKey]?.[String(st.lag)]?{event:ev,wind:ev.wind[st.windKey][String(st.lag)]}:null}
function pct(v){return v==null?"--":Math.round(v*100)+"%"}
function num(v,u=""){return v==null?"--":`${Number(v).toFixed(1)}${u}`}
function drawDiagnosisTable(event,st,rows){const diag=eventDiagnosis(event,st);let pmSync,wind,diagnosis;if(diag){pmSync=diag.event.pm_sync;wind=diag.wind;diagnosis=wind.diagnosis}else{const dayRows=rows.filter(r=>r.t>=`${event.date}T00:00`&&r.t<=`${event.date}T23:00`);pmSync={total:Object.keys(PM_NAMES).length,elevated_count:Object.keys(PM_NAMES).filter(k=>(pmValueAt(k,eventTime(event,0))??0)>=25).length,high_count:Object.keys(PM_NAMES).filter(k=>(pmValueAt(k,eventTime(event,0))??0)>=35).length};wind={mean_ws:dayRows.length?dayRows.reduce((a,b)=>a+b.ws,0)/dayRows.length:null,calm_ratio:dayRows.length?dayRows.filter(r=>r.ws<st.calm).length/dayRows.length:null,dominant_dir:"--",direction_stability:null,mean_rh:null,mean_temp_td_gap:null,rain_total:null,pressure_delta:null};diagnosis={label:classifyEvent(rows,event,st).label,flags:[]}}const flags=(diagnosis.flags||[]).map(zhFlag).join("、")||"沒有明顯單一訊號";const rowsHtml=[["診斷",zhClass(diagnosis.label),flags],["PM 測站同步",`${pmSync.elevated_count}/${pmSync.total} 站偏高，${pmSync.high_count} 站高濃度`,"判斷是否為區域事件，而非單一測站異常。"],["平均風速",num(wind.mean_ws," m/s"),"風速太低時，不宜用風向推論污染來源。"],["靜風比例",pct(wind.calm_ratio),"比例高代表累積或停滯條件較明顯。"],["主風向",wind.dominant_dir||"--","需搭配足夠風速與方向穩定度一起看。"],["風向穩定度",pct(wind.direction_stability),"越高代表高峰時窗內風向越一致。"],["平均 RH",num(wind.mean_rh,"%"),"高濕可能造成粒子吸濕成長或感測反應偏高。"],["溫度-露點差",num(wind.mean_temp_td_gap," C"),"差距小代表接近飽和，可能有霧霾條件。"],["時窗雨量",num(wind.rain_total," mm"),"降雨可能清除污染，也可能標記受雨影響資料。"],["氣壓變化",num(wind.pressure_delta," hPa"),"氣壓變化可提示氣團或鋒面轉換。"]];diagnosisTable.innerHTML=rowsHtml.map(([k,v,n])=>`<tr><td>${k}</td><td>${v}</td><td>${n}</td></tr>`).join("")}
function renderEvents(events,rows,st){eventList.innerHTML=events.map((e,i)=>{const cl=classifyEvent(rows,e,st);return`<div class="event ${i===selectedEvent?"active":""}" data-i="${i}"><div class="event-head"><span>#${e.rank} ${e.date}</span><span>${pad(e.peakH)}:00</span></div><div class="event-title">SP-05 ${e.peakV.toFixed(1)} ug/m3</div><span class="tag ${cl.type}">${zhClass(cl.label)}</span></div>`}).join("");eventList.querySelectorAll(".event").forEach(el=>el.addEventListener("click",()=>{selectedEvent=+el.dataset.i;eventSelect.value=selectedEvent;update()}))}
function renderDetail(event,st){const w=windMap(st.windKey),offsets=[-6,-4,-3,-2,-1,0,1];const selectedT=eventTime(event,st.offset);const steps=offsets.map(o=>{const pmT=eventTime(event,o),windT=addHours(pmT,-st.lag),wr=w[windT],calm=wr&&wr.WS<st.calm;return`<div class="step"><div class="t">${relativeToPeak(pmT,event)}<br>PM ${pmT.slice(11,16)}<br>風 ${relativeToPeak(windT,event)}</div><div class="wd ${calm?"calm":""}">${wr?calm?"靜風":wdName(wr.WD):"--"}</div><div class="ws">${wr?`${wr.WD} 度 / ${wr.WS} m/s`:"無風場資料"}</div></div>`}).join("");eventDetail.innerHTML=`<strong>高峰時間：${peakTime(event)}</strong><br>目前選中時間：${selectedT} (${relativeToPeak(selectedT,event)})。PM2.5 以絕對時間顯示；風場以「選中時間」為基準標示。目前風場設定：${lagText(st.lag)}。<div class="timeline">${steps}</div>`;const wr=w[addHours(eventTime(event,st.offset),-st.lag)]||{};weatherGrid.innerHTML=[["溫度",wr.Temp,"C"],["RH",wr.RH,"%"],["雨量",wr.Precp,"mm"],["陣風",wr.WSGust,"m/s"],["氣壓",wr.StnPres,"hPa"],["雲量",wr.Cloud,"/10"]].map(([k,v,u])=>`<div class="wbox"><div class="k">${k}</div><div class="v">${v==null?"--":v} ${v==null?"":u}</div></div>`).join("")}
function update(){const st=getState();selectedEvent=st.eventIndex;const events=allEvents(),event=events[selectedEvent];lagReadout.textContent=lagText(st.lag);offsetReadout.textContent=pmOffsetText(event,st.offset);const rows=aligned(st),stats=lagStats(st),best=stats.reduce((a,b)=>b.score>a.score?b:a,stats[0]),diag=eventDiagnosis(event,st),cl=diag?{label:diag.wind.diagnosis.label,why:(diag.wind.diagnosis.flags||[]).map(zhFlag).join("、")||"沒有明顯單一訊號"}:classifyEvent(rows,event,st),calmRatio=diag?.wind?.calm_ratio??(rows.length?rows.filter(r=>r.ws<st.calm).length/rows.length:0);mClass.textContent=zhClass(cl.label);mWhy.textContent=cl.why;mBestLag.textContent=lagText(best.lag);mPairs.textContent=rows.length;mCalm.textContent=(calmRatio*100).toFixed(0)+"%";renderEvents(events,rows,st);renderDetail(event,st);drawMap(st,event);drawLagChart(stats,st.lag);drawSeries(rows,event);drawPolar(rows,st);drawDiagnosisTable(event,st,rows)}
function init(){allEvents().forEach((e,i)=>eventSelect.add(new Option(`#${e.rank} ${e.date} ${pad(e.peakH)}:00`,i)));Object.keys(WIND_PM25_DATA.pm25_data).forEach(k=>pmSelect.add(new Option(PM_NAMES[k]||k,k)));Object.keys(WIND_PM25_DATA.wind_stations).forEach(k=>windSelect.add(new Option(WIND_NAMES[k]||k,k)));eventSelect.value="0";pmSelect.value="sp05_hourly";windSelect.value="xinyi";initMap();[eventSelect,pmSelect,windSelect,offsetRange,lagRange,calmInput].forEach(el=>el.addEventListener("input",update));update();setTimeout(()=>map.invalidateSize(),100)}
window.addEventListener("load",init);
